import { pool } from '../database';
import { ProductRepository } from './product.repository';
import { InventoryRepository } from './inventory.repository';
import { OrderRepository } from './order.repository';
import { OrderItemRepository } from './order-item.repository';
import { PickingTaskRepository } from './picking-task.repository';
import { PickingTaskItemRepository } from './picking-task-item.repository';
import { PackingRepository } from './packing.repository';
import { DispatchRepository } from './dispatch.repository';
import { ReturnRepository } from './return.repository';
import { ExceptionRepository } from './exception.repository';
import { RootCauseAnalysisRepository } from './root-cause-analysis.repository';
import { ExceptionRecommendationRepository } from './exception-recommendation.repository';
import { ActionRepository } from './action.repository';
import { ActionOutcomeRepository } from './action-outcome.repository';
import { PredictionRepository } from './prediction.repository';

export * from './product.repository';
export * from './inventory.repository';
export * from './order.repository';
export * from './order-item.repository';
export * from './picking-task.repository';
export * from './picking-task-item.repository';
export * from './packing.repository';
export * from './dispatch.repository';
export * from './return.repository';
export * from './exception.repository';
export * from './root-cause-analysis.repository';
export * from './exception-recommendation.repository';
export * from './action.repository';
export * from './action-outcome.repository';
export * from './prediction.repository';

export const productRepository = new ProductRepository(pool);
export const inventoryRepository = new InventoryRepository(pool);
export const orderRepository = new OrderRepository(pool);
export const orderItemRepository = new OrderItemRepository(pool);
export const pickingTaskRepository = new PickingTaskRepository(pool);
export const pickingTaskItemRepository = new PickingTaskItemRepository(pool);
export const packingRepository = new PackingRepository(pool);
export const dispatchRepository = new DispatchRepository(pool);
export const returnRepository = new ReturnRepository(pool);
export const exceptionRepository = new ExceptionRepository(pool);
export const rootCauseAnalysisRepository = new RootCauseAnalysisRepository(pool);
export const exceptionRecommendationRepository = new ExceptionRecommendationRepository(pool);
export const actionRepository = new ActionRepository(pool);
export const actionOutcomeRepository = new ActionOutcomeRepository(pool);
export const predictionRepository = new PredictionRepository(pool);
